schema: 1

name:             IC2 Classic
author:           Alblaka
description:      This is an older version of Industrial Craft 2 (before the "experimental" rewrite) ported for modern Minecraft versions.
homePageUrl:      http://wiki.industrial-craft.net/
documentationUrl: http://wiki.industrial-craft.net/
downloadUrl:      http://wiki.industrial-craft.net/index.php?title=Recipes_and_Resources

version: 1.7.10-6
