schema: 1

description: <<-END
The Silver Chest takes up a single block but offers 8 rows of storage (as compared to 3 in a regular [Chest]). That
makes for 72 slots total capacity.

In addition to its regular crafting recipe, one can upgrade a [Copper Chest] to a Silver Chest by right-clicking it with
a [Copper to Silver Chest Upgrade].

The Silver Chest can itself be upgraded to a [Gold Chest] by using an [Silver to Gold Chest Upgrade] on it.
END
