schema: 1

item: 10K Coolant Cell
    recipe:
        extras: Bucket
        input: Tin Ingot, Water Bucket
        pattern: .0. 010 .0.
        tools: Crafting Table

item: 2x Ins. Gold Cable
    recipe:
        input: Gold Cable, Rubber
        pattern: ... 101 ...
    recipe:
        input: Insulated Gold Cable, Rubber
        pattern: ... .0. .1.

item: 2x Ins. HV Cable
    recipe:
        input: HV Cable, Rubber
        pattern: ... 101 ...
    recipe:
        input: Insulated HV Cable, Rubber
        pattern: ... .0. .1.

item: 30K Coolant Cell
    recipe:
        input: 10K Coolant Cell, Tin Ingot
        pattern: 111 000 111
        tools: Crafting Table

item: 4x Ins. HV Cable
    recipe:
        input: HV Cable, Rubber
        pattern: ... 111 .0.
    recipe:
        input: Insulated HV Cable, Rubber
        pattern: ... 101 ...
    recipe:
        input: HV 2x Insulated Cable, Rubber
        pattern: ... .0. .1.

item: 60K Coolant Cell
    recipe:
        input: 30K Coolant Cell, Dense Copper Plate, Tin Ingot
        pattern: 202 212 202
        tools: Crafting Table

item: Advanced Alloy
    recipe:
        input: Mixed Metal Ingot
        pattern: ... .0. ...
        tools: Compressor

item: Advanced Circuit
    recipe:
        input: Electronic Circuit, Glowstone Dust, Lapis Lazuli, Redstone
        pattern: 313 202 313
        tools: Crafting Table

item: Advanced Heat Exchanger
    recipe:
        input: Dense Copper Plate, Electronic Circuit, Glass Fibre Cable, Heat Exchanger
        pattern: 212 303 212
        tools: Crafting Table

item: Advanced Heat Vent
    recipe:
        input: Diamond, Heat Vent, Iron Bars
        pattern: 212 202 212
        tools: Crafting Table

item: Advanced Machine Block
    recipe:
        input: Advanced Alloy, Carbon Plate, Machine Block
        pattern: .0. 121 .0.
        tools: Crafting Table

item: BatBox
    recipe:
        input: Insulated Copper Cable, Oak Wood Planks, RE Battery
        pattern: 101 222 111
        tools: Crafting Table

item: BatPack
    recipe:
        input: Electronic Circuit, RE Battery, Tin Ingot
        pattern: 101 121 1.1
        tools: Crafting Table

item: Bio Cell
    recipe:
        input: Compressed Plants, Empty Cell
        pattern: ... .0. .1.

item: Biofuel Cell
    recipe:
        input: Bio Cell
        pattern: ... .0. ...
        tools: Extractor

item: Bronze Axe
    recipe:
        input: Bronze Ingot, Stick
        pattern: 00. 01. .1.
        tools: Crafting Table

item: Bronze Block
    recipe:
        input: Bronze Ingot
        pattern: 000 000 000
        tools: Crafting Table

item: Bronze Boots
    recipe:
        input: Bronze Ingot
        pattern: ... 0.0 0.0
        tools: Crafting Table

item: Bronze Chestplate
    recipe:
        input: Bronze Ingot
        pattern: 0.0 000 000
        tools: Crafting Table

item: Bronze Dust
    recipe:
        input: Copper Dust, Tin Dust
        pattern: 10. 00. ...
        quantity: 2

item: Bronze Helmet
    recipe:
        input: Bronze Ingot
        pattern: 000 0.0 ...
        tools: Crafting Table

item: Bronze Hoe
    recipe:
        input: Bronze Ingot, Stick
        pattern: 00. .1. .1.
        tools: Crafting Table

item: Bronze Ingot
    recipe:
        input: Bronze Dust, furnace fuel
        pattern: .0. ... .1.
        tools: Furnace

item: Bronze Leggings
    recipe:
        input: Bronze Ingot
        pattern: 000 0.0 0.0
        tools: Crafting Table

item: Bronze Pickaxe
    recipe:
        input: Bronze Ingot, Stick
        pattern: 000 .1. .1.
        tools: Crafting Table

item: Bronze Shovel
    recipe:
        input: Bronze Ingot, Stick
        pattern: .0. .1. .1.
        tools: Crafting Table

item: Bronze Sword
    recipe:
        input: Bronze Ingot, Stick
        pattern: .0. .0. .1.
        tools: Crafting Table

item: Canning Machine
    recipe:
        input: Electronic Circuit, Machine Block, Tin Ingot
        pattern: 202 212 222
        tools: Crafting Table

item: Carbon Plate
    recipe:
        input: Raw Carbon Mesh
        pattern: ... .0. ...
        tools: Compressor

item: CF Backpack
    recipe:
        input: (empty) Fuel Can, CF Sprayer, Electronic Circuit, Tin Ingot
        pattern: 121 030 0.0
        tools: Crafting Table

item: CF Pellet
    recipe:
        input: Construction Foam
        pattern: ... .0. ...
        tools: Compressor

item: CF Sprayer
    recipe:
        input: Cobblestone, Stick
        pattern: 00. 01. ..0
        tools: Crafting Table

item: Chainsaw
    recipe:
        input: Electronic Circuit, RE Battery, Refined Iron
        pattern: .22 202 12.
        tools: Crafting Table

item: Clay Dust
    recipe:
        input: Clay Block
        pattern: ... .0. ...
        tools: Macerator

item: Coal Ball
    recipe:
        input: Coal Dust, Flint
        pattern: 000 010 000
        tools: Crafting Table

item: Coal Chunk
    recipe:
        input: Compressed Coal Ball, Obsidian
        pattern: 000 010 000
        tools: Crafting Table
    recipe:
        input: Bricks, Compressed Coal Ball
        pattern: 111 101 111
        tools: Crafting Table
    recipe:
        input: Compressed Coal Ball, Iron Block
        pattern: 000 010 000
        tools: Crafting Table

item: Coal Dust
    recipe:
        input: Coal
        pattern: ... .0. ...
        tools: Macerator

item: Coalfuel Cell
    recipe:
        input: H. Coal Cell
        pattern: ... .0. ...
        tools: Extractor

item: Coffee Beans
    gatherable: yes

item: Coffee Powder
    recipe:
        input: Coffee Beans
        pattern: ... .0. ...
        quantity: 3
        tools: Macerator

item: Component Heat Exchanger
    recipe:
        input: Gold Ingot, Heat Exchanger
        pattern: .0. 010 .0.
        tools: Crafting Table

item: Composite Vest
    recipe:
        input: Advanced Alloy, Iron Chestplate, Leather Tunic
        pattern: 0.0 010 020
        tools: Crafting Table

item: Compressed Air Cell
    recipe:
        input: Empty Cell
        pattern: ... .0. ...
        tools: Compressor

item: Compressed Coal Ball
    recipe:
        input: Coal Ball
        pattern: ... .0. ...
        tools: Compressor

item: Compressed Hyd. Coalclump
    recipe:
        input: Hydrated Coal Dust
        pattern: ... .0. ...
        tools: Compressor

item: Compressed Plants
    recipe:
        input: Plantball
        pattern: ... .0. ...
        tools: Compressor

item: Compressor
    recipe:
        input: Electronic Circuit, Machine Block, Stone
        pattern: 2.2 202 212
        tools: Crafting Table

item: Construction Foam
    recipe:
        extras: Bucket
        input: Clay Dust, Coal Dust, Redstone, Water Bucket
        pattern: 01. 23. ...

item: Containment Reactor Plating
    recipe:
        input: Advanced Alloy, Reactor Plating
        pattern: ... 010 ...

item: Copper Block
    recipe:
        input: Copper Ingot
        pattern: 000 000 000
        tools: Crafting Table

item: Copper Cable
    recipe:
        input: Copper Ingot
        pattern: ... 000 ...
        quantity: 6
        tools: Crafting Table

item: Copper Dust
    recipe:
        input: Copper Ore
        pattern: ... .0. ...
        quantity: 2
        tools: Macerator

item: Copper Ingot
    recipe:
        input: Copper Ore, furnace fuel
        pattern: .0. ... .1.
        tools: Furnace

item: Copper Ore
    gatherable: yes

item: Crop
    recipe:
        input: Stick
        pattern: ... 0.0 0.0
        quantity: 2
        tools: Crafting Table

item: Crop-Matron
    recipe:
        input: Chest, Crop, Electronic Circuit, Machine Block
        pattern: 202 131 111
        tools: Crafting Table

item: Cropnalyzer
    recipe:
        input: Electronic Circuit, Glass, Insulated Copper Cable, Redstone
        pattern: 22. 313 303
        tools: Crafting Table

item: Dense Copper Plate
    recipe:
        input: Copper Ingot
        pattern: 000 0.0 000
        tools: Compressor

item: Depleted Isotope Cell
    recipe:
        input: Coal Dust, Near-Depleted Uranium Cell
        pattern: ... .0. .1.
        tools: Crafting Table

item: Diamond Drill
    recipe:
        input: Diamond, Mining Drill
        pattern: ... .0. 010
        tools: Crafting Table

item: Diamond (industrial)
    recipe:
        input: Coal Chunk
        pattern: ... .0. ...
        tools: Compressor

item: Dual Uranium Cell
    recipe:
        input: Dense Copper Plate, Uranium Cell
        pattern: ... 101 ...
        tools: Crafting Table

item: Dynamite
    recipe:
        input: Industrial TNT, String
        pattern: ... .1. .0.
        quantity: 8
        tools: Crafting Table

item: Dynamite-O-Mote
    recipe:
        input: Electronic Circuit, Glowstone Dust, Insulated Copper Cable, TNT
        pattern: .2. 101 333
        tools: Crafting Table

item: Electric Furnace
    recipe:
        input: Electronic Circuit, Iron Furnace, Redstone
        pattern: ... .0. 212
        tools: Crafting Table

item: Electric Hoe
    recipe:
        input: Electronic Circuit, RE Battery, Refined Iron
        pattern: 22. .0. .1.
        tools: Crafting Table

item: Electric Jetpack
    recipe:
        input: Advanced Circuit, BatBox, Glowstone Dust, Refined Iron
        pattern: 303 313 2.2
        tools: Crafting Table

item: Electric Treetap
    recipe:
        input: Electronic Circuit, RE Battery, Treetap
        pattern: ..2 .0. 1..
        tools: Crafting Table

item: Electric Wrench
    recipe:
        input: Electronic Circuit, RE Battery, Wrench
        pattern: ..2 .1. 0..
        tools: Crafting Table

item: Electrolyzer
    recipe:
        input: Electronic Circuit, Insulated Copper Cable, Machine Block, RE Battery
        pattern: 1.1 101 323
        tools: Crafting Table

item: Electronic Circuit
    recipe:
        input: Insulated Copper Cable, Redstone, Refined Iron
        pattern: 000 121 000
        tools: Crafting Table

item: Empty Booze Barrel
    recipe:
        input: Oak Wood Planks, Rubber Wood
        pattern: .0. .1. .0.
        tools: Crafting Table

item: Empty Cell
    recipe:
        input: Tin Ingot
        pattern: .0. 0.0 .0.
        quantity: 16
        tools: Crafting Table

item: (Empty) Fuel Can
    recipe:
        input: Tin Ingot
        pattern: .00 0.0 000
        tools: Crafting Table

item: Energy Crystal
    recipe:
        input: Diamond, Redstone
        pattern: 111 101 111
        tools: Crafting Table

item: Energy Storage Upgrade
    recipe:
        input: Electronic Circuit, Insulated Copper Cable, Oak Wood Planks, RE Battery
        pattern: 222 101 232
        tools: Crafting Table

item: EU Detector Cable
    recipe:
        input: 4x Ins. HV Cable, Electronic Circuit, Redstone
        pattern: .1. 202 .2.
        tools: Crafting Table

item: EU Reader
    recipe:
        input: Electronic Circuit, Glowstone Dust, Insulated Copper Cable
        pattern: .1. 202 2.2
        tools: Crafting Table

item: EU-Splitter Cable
    recipe:
        input: 4x Ins. HV Cable, Lever, Redstone
        pattern: .2. 010 .2.

item: Extractor
    recipe:
        input: Electronic Circuit, Machine Block, Treetap
        pattern: ... 212 202
        tools: Crafting Table

item: Fertilizer
    recipe:
        input: Bone Meal, Scrap
        pattern: ... .1. .0.
        quantity: 2
    recipe:
        input: Fertilizer, Scrap
        pattern: ... 101 ...
        quantity: 2

item: (filled) Fuel Can
    recipe:
        input: (empty) Fuel Can, Coalfuel Cell
        pattern: 111 111 .0.
        tools: Canning Machine
    recipe:
        input: (empty) Fuel Can, Biofuel Cell
        pattern: 111 111 .0.
        tools: Canning Machine

item: (Filled) Tin Can
    recipe:
        input: Bread, Tin Can
        pattern: ... .0. 111
        quantity: 3
        tools: Canning Machine

item: Frequency Transmitter
    recipe:
        input: Electronic Circuit, Insulated Copper Cable
        pattern: ... .1. .0.
        tools: Crafting Table

item: Generator
    recipe:
        input: Furnace, Machine Block, RE Battery
        pattern: .2. .1. .0.
        tools: Crafting Table
    recipe:
        input: Iron Furnace, RE Battery, Refined Iron
        pattern: .1. 222 .0.
        tools: Crafting Table

item: Geothermal Generator
    recipe:
        input: Empty Cell, Generator, Glass, Refined Iron
        pattern: 202 202 313
        tools: Crafting Table

item: Glass Fibre Cable
    recipe:
        input: Diamond, Glass, Redstone
        pattern: 111 202 111
        quantity: 4
        tools: Crafting Table

item: Gold Cable
    recipe:
        input: Gold Ingot
        pattern: ... 000 ...
        quantity: 12
        tools: Crafting Table

item: Gold Dust
    recipe:
        input: Gold Ore
        pattern: ... .0. ...
        quantity: 2
        tools: Macerator

item: Grin Powder
    recipe:
        input: Spider Eye
        pattern: ... .0. ...
        quantity: 2
        tools: Macerator

item: H. Coal Cell
    recipe:
        input: Compressed Hyd. Coalclump, Empty Cell
        pattern: ... .0. .1.

item: Hazmat Suit
    recipe:
        input: Orange Dye, Rubber
        pattern: 1.1 101 101
        tools: Crafting Table

item: Hazmat Suit Leggings
    recipe:
        input: Orange Dye, Rubber
        pattern: 101 1.1 1.1
        tools: Crafting Table

item: Heat-Capacity Reactor Plating
    recipe:
        input: Dense Copper Plate, Reactor Plating
        pattern: ... 010 ...

item: Heat Exchanger
    recipe:
        input: Dense Copper Plate, Electronic Circuit, Tin Ingot
        pattern: .1. 202 .2.
        tools: Crafting Table

item: Heat Vent
    recipe:
        input: Iron Bars, Refined Iron
        pattern: 101 0.0 101
        tools: Crafting Table

item: Heating Cell
    recipe:
        input: Dense Copper Plate, Electronic Circuit, Lava Cell
        pattern: .1. .2. .0.
        tools: Crafting Table

item: HV Cable
    recipe:
        input: Refined Iron
        pattern: ... 000 ...
        quantity: 12
        tools: Crafting Table

item: HV Transformer
    recipe:
        input: 4x Ins. HV Cable, Electronic Circuit, Energy Crystal, MV Transformer
        pattern: .0. 132 .0.
        tools: Crafting Table

item: Hydrated Coal Dust
    recipe:
        extras: Bucket
        input: Coal Dust, Water Bucket
        pattern: 000 010 000
        quantity: 8
        tools: Crafting Table

item: Hydration Cell
    recipe:
        input: Water Cell
        pattern: ... .0. ...
        tools: Extractor

item: Induction Furnace
    recipe:
        input: Advanced Machine Block, Copper Ingot, Electric Furnace
        pattern: 111 121 101
        tools: Crafting Table

item: Industrial TNT
    recipe:
        input: Flint, TNT
        pattern: 000 111 000
        quantity: 4
        tools: Crafting Table

item: Insulated Copper Cable
    recipe:
        input: Copper Cable, Rubber
        pattern: ... .0. .1.

item: Insulated Gold Cable
    recipe:
        input: Gold Cable, Rubber
        pattern: ... .0. .1.

item: Insulated HV Cable
    recipe:
        input: HV Cable, Rubber
        pattern: ... .0. .1.

item: Insulation Cutter
    recipe:
        input: Iron Ingot, Refined Iron
        pattern: 1.1 .1. 0.0
        tools: Crafting Table

item: Iridium Ore
    recipe:
        input: UU Matter
        pattern: 000 .0. 000
        tools: Crafting Table

item: Iridium Plate
    recipe:
        input: Advanced Alloy, Diamond, Iridium Ore
        pattern: 202 010 202
        tools: Crafting Table

item: Iron Dust
    recipe:
        input: Iron Ore
        pattern: ... .0. ...
        quantity: 2
        tools: Macerator

item: Iron Fence
    recipe:
        input: Iron Ingot
        pattern: ... 000 000
        quantity: 12
        tools: Crafting Table

item: Iron Furnace
    recipe:
        input: Iron Ingot
        pattern: 000 0.0 000
        tools: Crafting Table
    recipe:
        input: Furnace, Iron Ingot
        pattern: .1. 1.1 101
        tools: Crafting Table

item: Iron Scaffold
    recipe:
        input: Iron Fence, Refined Iron
        pattern: 111 .0. 0.0
        quantity: 16
        tools: Crafting Table

item: Jetpack
    recipe:
        input: (empty) Fuel Can, Electronic Circuit, Redstone, Refined Iron
        pattern: 313 303 2.2
        tools: Crafting Table

item: Lapotron Crystal
    recipe:
        input: Electronic Circuit, Energy Crystal, Lapis Lazuli
        pattern: 202 212 202
        tools: Crafting Table

item: LapPack
    recipe:
        input: Advanced Circuit, BatPack, Lapis Lazuli Block
        pattern: 202 212 2.2
        tools: Crafting Table

item: Lava Cell
    recipe:
        extras: Bucket
        input: Empty Cell, Lava Bucket
        pattern: ... .1. .0.

item: Luminator
    recipe:
        input: Glass, Insulated Copper Cable, Refined Iron, Ultra Low Current Cable
        pattern: 212 030 000
        quantity: 8
        tools: Crafting Table

item: LV Transformer
    recipe:
        input: Copper Ingot, Insulated Copper Cable, Oak Wood Planks
        pattern: 212 000 212
        tools: Crafting Table

item: LZH-Condensator
    recipe:
        input: Lapis Lazuli Block, RSH-Condensator, Reactor Heat Exchanger, Reactor Heat Vent, Redstone
        pattern: 434 101 424
        tools: Crafting Table

item: Macerator
    recipe:
        input: Cobblestone, Electronic Circuit, Flint, Machine Block
        pattern: 222 030 .1.
        tools: Crafting Table

item: Machine Block
    recipe:
        input: Refined Iron
        pattern: 000 0.0 000
        tools: Crafting Table

item: Magnetizer
    recipe:
        input: Iron Fence, Machine Block, Redstone
        pattern: 202 212 202
        tools: Crafting Table

item: Mass Fabricator
    recipe:
        input: Advanced Circuit, Advanced Machine Block, Glowstone Dust, Lapotron Crystal
        pattern: 202 131 202
        tools: Crafting Table

item: MFE
    recipe:
        input: 2x Ins. Gold Cable, Energy Crystal, Machine Block
        pattern: 010 121 010
        tools: Crafting Table

item: MFSU
    recipe:
        input: Advanced Circuit, Advanced Machine Block, Lapotron Crystal, MFE
        pattern: 202 232 212
        tools: Crafting Table

item: Miner
    recipe:
        input: Electronic Circuit, Machine Block, Mining Pipe
        pattern: 010 .2. .2.
        tools: Crafting Table

item: Mining Drill
    recipe:
        input: Electronic Circuit, RE Battery, Refined Iron
        pattern: .2. 202 212
        tools: Crafting Table

item: Mining Laser
    recipe:
        input: Advanced Alloy, Advanced Circuit, Energy Crystal, Redstone
        pattern: 322 001 .00
        tools: Crafting Table

item: Mining Pipe
    recipe:
        input: Refined Iron, Treetap
        pattern: 0.0 0.0 010
        quantity: 8
        tools: Crafting Table

item: Mixed Metal Ingot
    recipe:
        input: Bronze Ingot, Refined Iron, Tin Ingot
        pattern: 111 000 222
        quantity: 2
        tools: Crafting Table

item: MV Transformer
    recipe:
        input: 2x Ins. Gold Cable, Machine Block
        pattern: .0. .1. .0.
        tools: Crafting Table

item: Nano Saber
    recipe:
        input: Advanced Alloy, Carbon Plate, Energy Crystal, Glowstone Dust
        pattern: 31. 31. 020
        tools: Crafting Table

item: NanoSuit Bodyarmor
    recipe:
        input: Carbon Plate, Energy Crystal
        pattern: 0.0 010 000
        tools: Crafting Table

item: NanoSuit Boots
    recipe:
        input: Carbon Plate, Energy Crystal
        pattern: ... 0.0 010
        tools: Crafting Table

item: NanoSuit Helmet
    recipe:
        input: Carbon Plate, Energy Crystal, Glass
        pattern: 010 020 ...
        tools: Crafting Table

item: NanoSuit Leggings
    recipe:
        input: Carbon Plate, Energy Crystal
        pattern: 010 0.0 0.0
        tools: Crafting Table

item: Near-Depleted Uranium Cell
    recipe:
        input: Empty Cell, Refined Uranium
        pattern: 000 010 000
        tools: Crafting Table

item: Neutron Reflector
    recipe:
        input: Coal Dust, Dense Copper Plate, Tin Dust
        pattern: 202 212 202
        tools: Crafting Table

item: Nuclear Reactor
    recipe:
        input: Advanced Circuit, Generator, Reactor Chamber
        pattern: .0. 222 .1.
        tools: Crafting Table

item: OD Scanner
    recipe:
        input: Electronic Circuit, Glowstone Dust, Insulated Copper Cable, RE Battery
        pattern: .1. 030 222
        tools: Crafting Table

item: OV Scanner
    recipe:
        input: 2x Ins. Gold Cable, Advanced Circuit, Glowstone Dust, OD Scanner
        pattern: .2. 212 030
        tools: Crafting Table

item: Overclocked Heat Vent
    recipe:
        input: Gold Ingot, Reactor Heat Vent
        pattern: .0. .1. .0.
        tools: Crafting Table

item: Overclocker Upgrade
    recipe:
        input: 10K Coolant Cell, Electronic Circuit, Insulated Copper Cable
        pattern: ... 000 212
        tools: Crafting Table

item: Painter
    recipe:
        input: Iron Ingot, Wool
        pattern: .11 .01 0..
        tools: Crafting Table

item: Personal Safe
    recipe:
        input: Chest, Electronic Circuit, Machine Block
        pattern: .1. .2. .0.
        tools: Crafting Table

item: Plantball
    recipe:
        input: Wheat
        pattern: 000 0.0 000
        tools: Crafting Table
    recipe:
        input: Sugar Cane
        pattern: 000 0.0 000
        tools: Crafting Table
    recipe:
        input: Seeds
        pattern: 000 0.0 000
        tools: Crafting Table
    recipe:
        input: Melon Seeds
        pattern: 000 0.0 000
        tools: Crafting Table
    recipe:
        input: Pumpkin Seeds
        pattern: 000 0.0 000
        tools: Crafting Table
    recipe:
        input: Oak Leaves
        pattern: 000 0.0 000
        tools: Crafting Table
    recipe:
        input: Oak Sapling
        pattern: 000 0.0 000
        quantity: 2
        tools: Crafting Table

item: Pump
    recipe:
        input: Electronic Circuit, Empty Cell, Machine Block, Mining Pipe, Treetap
        pattern: 101 121 343
        tools: Crafting Table

item: Quad Uranium Cell
    recipe:
        input: Dense Copper Plate, Dual Uranium Cell
        pattern: .1. 000 .1.
        tools: Crafting Table

item: QuantumSuit Bodyarmor
    recipe:
        input: Advanced Alloy, Iridium Plate, Lapotron Crystal, NanoSuit Bodyarmor
        pattern: 030 121 101
        tools: Crafting Table

item: QuantumSuit Boots
    recipe:
        input: Iridium Plate, Lapotron Crystal, NanoSuit Boots, Rubber Boots
        pattern: ... 020 313
        tools: Crafting Table

item: QuantumSuit Helmet
    recipe:
        input: Advanced Circuit, Iridium Plate, Lapotron Crystal, NanoSuit Helmet, Reinforced Glass
        pattern: .3. 121 040
        tools: Crafting Table

item: QuantumSuit Leggings
    recipe:
        input: Glowstone Dust, Iridium Plate, Lapotron Crystal, Machine Block, NanoSuit Leggings
        pattern: 323 141 0.0
        tools: Crafting Table

item: Raw Carbon Fibre
    recipe:
        input: Coal Dust
        pattern: 00. 00. ...

item: Raw Carbon Mesh
    recipe:
        input: Raw Carbon Fibre
        pattern: ... .0. .0.

item: RE Battery
    recipe:
        input: Insulated Copper Cable, Redstone, Tin Ingot
        pattern: .0. 212 212
        tools: Crafting Table

item: Reactor Chamber
    recipe:
        input: Dense Copper Plate, Machine Block
        pattern: .0. 010 .0.
        tools: Crafting Table

item: Reactor Heat Exchanger
    recipe:
        input: Dense Copper Plate, Heat Exchanger
        pattern: .0. .1. .0.
        tools: Crafting Table

item: Reactor Heat Vent
    recipe:
        input: Dense Copper Plate, Heat Vent
        pattern: .0. .1. .0.
        tools: Crafting Table

item: Reactor Plating
    recipe:
        input: Advanced Alloy, Dense Copper Plate
        pattern: ... .0. .1.

item: Recycler
    recipe:
        input: Compressor, Dirt, Glowstone Dust, Refined Iron
        pattern: .2. 101 313
        tools: Crafting Table

item: Refined Iron
    recipe:
        input: Iron Ingot, furnace fuel
        pattern: .0. ... .1.
        tools: Furnace

item: Refined Uranium
    recipe:
        input: Uranium
        pattern: ... .0. ...
        tools: Compressor

item: Reinforced Door
    recipe:
        input: Reinforced Stone
        pattern: .00 .00 .00
        tools: Crafting Table

item: Reinforced Glass
    recipe:
        input: Advanced Alloy, Glass
        pattern: 111 010 111
        quantity: 7
        tools: Crafting Table

item: Reinforced Stone
    recipe:
        input: Advanced Alloy, Stone
        pattern: 111 101 111
        quantity: 8
        tools: Crafting Table

item: RSH-Condensator
    recipe:
        input: Heat Exchanger, Heat Vent, Redstone
        pattern: 222 212 202
        tools: Crafting Table

item: Rubber
    recipe:
        input: Sticky Resin, furnace fuel
        pattern: .0. ... .1.
        tools: Furnace

item: Rubber Boots
    recipe:
        input: Rubber, Wool
        pattern: 0.0 0.0 010
        tools: Crafting Table

item: Rubber Sheet
    recipe:
        input: Rubber
        pattern: ... 000 000
        tools: Crafting Table

item: Rubber Wood
    gatherable: yes

item: Scaffold
    recipe:
        input: Oak Wood Planks, Stick
        pattern: 000 .1. 1.1
        quantity: 16
        tools: Crafting Table

item: Scrap
    gatherable: yes

item: Scrap Box
    recipe:
        input: Scrap
        pattern: 000 000 000
        tools: Crafting Table

item: Scuba Helmet
    recipe:
        input: Glass, Iron Bars, Orange Dye, Rubber
        pattern: .2. 303 313
        tools: Crafting Table

item: Single-Use Battery
    recipe:
        input: Hydrated Coal Dust, Insulated Copper Cable, Redstone
        pattern: .1. .2. .0.
        quantity: 8
        tools: Crafting Table
    recipe:
        input: Coal Dust, Insulated Copper Cable, Redstone
        pattern: .1. .2. .0.
        quantity: 5
        tools: Crafting Table

item: Solar Helmet
    recipe:
        input: Insulated Copper Cable, Iron Ingot, Solar Panel
        pattern: 111 121 000
        tools: Crafting Table

item: Solar Panel
    recipe:
        input: Coal Dust, Electronic Circuit, Generator, Glass
        pattern: 030 303 121
        tools: Crafting Table

item: Static Boots
    recipe:
        input: Insulated Copper Cable, Iron Ingot, Wool
        pattern: 1.1 121 000
        tools: Crafting Table

item: Sticky Dynamite
    recipe:
        input: Dynamite, Sticky Resin
        pattern: 000 010 000
        quantity: 8
        tools: Crafting Table

item: Sticky Resin
    gatherable: yes

item: Stone Mug
    recipe:
        input: Stone
        pattern: 00. 000 00.
        tools: Crafting Table

item: Terraformer
    recipe:
        input: Advanced Machine Block, Dirt, Glowstone Dust, TFBP - Empty
        pattern: 232 101 212
        tools: Crafting Table

item: Tesla Coil
    recipe:
        input: Electronic Circuit, MV Transformer, Redstone, Refined Iron
        pattern: 222 212 303
        tools: Crafting Table

item: TFBP - Chilling
    recipe:
        input: Snowball, TFBP - Empty
        pattern: .0. 010 .0.
        tools: Crafting Table

item: TFBP - Cultivation
    recipe:
        input: Seeds, TFBP - Empty
        pattern: .0. 010 .0.
        tools: Crafting Table

item: TFBP - Desertification
    recipe:
        input: Sand, TFBP - Empty
        pattern: .0. 010 .0.
        tools: Crafting Table

item: TFBP - Empty
    recipe:
        input: Advanced Circuit, Electronic Circuit, Redstone
        pattern: .1. .0. 2.2
        tools: Crafting Table

item: TFBP - Flatification
    recipe:
        input: Dirt, TFBP - Empty
        pattern: .0. 010 .0.
        tools: Crafting Table

item: TFBP - Irrigation
    recipe:
        input: TFBP - Empty, Water Bucket
        pattern: .1. 101 .1.
        tools: Crafting Table

item: Thick Neutron Reflector
    recipe:
        input: Dense Copper Plate, Neutron Reflector
        pattern: .1. 101 .1.
        tools: Crafting Table

item: Tin Block
    recipe:
        input: Tin Ingot
        pattern: 000 000 000
        tools: Crafting Table

item: Tin Can
    recipe:
        input: Tin Ingot
        pattern: ... 0.0 000
        quantity: 4
        tools: Crafting Table

item: Tin Dust
    recipe:
        input: Tin Ore
        pattern: ... .0. ...
        quantity: 2
        tools: Macerator

item: Tin Ingot
    recipe:
        input: Tin Ore, furnace fuel
        pattern: .0. ... .1.
        tools: Furnace

item: Tin Ore
    gatherable: yes

item: Tool Box
    recipe:
        input: Chest, Iron Ingot
        pattern: ... 101 111
        tools: Crafting Table

item: Trade-O-Mat
    recipe:
        input: Chest, Machine Block, Redstone
        pattern: ... 222 010
        tools: Crafting Table

item: Transformer Upgrade
    recipe:
        input: 2x Ins. Gold Cable, Electronic Circuit, Glass, MV Transformer
        pattern: 222 030 212
        tools: Crafting Table

item: Treetap
    recipe:
        input: Oak Wood Planks
        pattern: .0. 000 0..
        tools: Crafting Table

item: Ultra Low Current Cable
    recipe:
        input: Tin Ingot
        pattern: ... 000 ...
        quantity: 9
        tools: Crafting Table

item: Uranium
    gatherable: yes

item: Uranium Block
    recipe:
        input: Refined Uranium
        pattern: 000 000 000
        tools: Crafting Table

item: Uranium Cell
    recipe:
        input: Empty Cell, Refined Uranium
        pattern: ... .0. .1.

item: UU Matter
    gatherable: yes

item: Water Cell
    recipe:
        extras: Bucket
        input: Empty Cell, Water Bucket
        pattern: ... .0. .1.

item: Water Mill
    recipe:
        input: Generator, Oak Wood Planks, Stick
        pattern: 212 101 212
        quantity: 2
        tools: Crafting Table

item: Weed-EX
    recipe:
        input: Empty Cell, Grin Powder, Redstone
        pattern: .1. .2. .0.
        tools: Crafting Table

item: Wind Mill
    recipe:
        input: Generator, Iron Ingot
        pattern: 1.1 .0. 1.1
        tools: Crafting Table

item: Wrench
    recipe:
        input: Bronze Ingot
        pattern: 0.0 000 .0.
        tools: Crafting Table

update: Nether Brick
    recipe:
        input: Netherrack
        pattern: .0. .0. .0.
        tools: Compressor

update: Blaze Powder
    recipe:
        input: Blaze Rod
        pattern: ... .0. ...
        quantity: 5
        tools: Macerator

update: Bone Meal
    recipe:
        input: Bone
        pattern: ... .0. ...
        quantity: 5
        tools: Macerator

update: Ice
    recipe:
        input: Snowball
        pattern: ... .0. ...
        tools: Compressor

update: Snowball
    recipe:
        input: Water Cell
        pattern: ... .0. ...
        tools: Compressor

update: String
    recipe:
        input: Wool
        pattern: ... .0. ...
        quantity: 4
        tools: Macerator