schema: 1

name:             Ender Storage
author:           chicken_bones
description:      This mod offers means to store your items in The END, causing them to be everywhere and nowhere at the same time.
homePageUrl:      http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods
documentationUrl: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods
downloadUrl:      http://chickenbones.net/Pages/links.html

version: 1.4.5.29
