schema: 1

description: <<-END
The Crystal Chest takes up a single block but offers 12 rows of storage (as compared to 3 in a regular wooden [Chest]).
That makes for 108 slots total capacity.  This is exactly the same as a [Diamond Chest], but, unlike a Diamond Chest, a
Crystal chest is transparent and will show off items inside.

In addition to its regular crafting recipe, one can upgrade a Diamond Chest to a Crystal Chest by right-clicking it with
a [Diamond to Crystal Chest Upgrade].
END
