schema: 1

name:             Forestry
author:           SirSengir, CovertJaguar, MysteriousAges
description:      Forestry deals with farming, renewable energy production as well as the breeding of trees, bees and butterflies in Minecraft.
homePageUrl:      http://forestry.sengir.net
documentationUrl: http://forestry.sengir.net/wiki.new/doku.php
downloadUrl:      http://minecraft.curseforge.com/mc-mods/59751-forestry/files

version: 3.4.0.7
