schema: 1

name:             Industrial Craft 2
author:           Alblaka
description:      A technical mod adding multi-tiered power systems, mining and ore processing, and powered armor
homePageUrl:      http://wiki.industrial-craft.net/
documentationUrl: http://wiki.industrial-craft.net/
downloadUrl:      http://jenkins.ic2.player.to/job/IC2_experimental/

version: experimental-2.2.663
version: classic-1.7.10-6
