#!/bin/bash

USAGE=<<END
USAGE: all <command>

    Executes a command for this project and each project related to this one.
    Related projects must include this project's name as a prefix in their name
    to be considered related.

END

COMMAND="$1"
[[ "$COMMAND" == "" ]] && echo $USAGE && exit 1

SRC_ROOT="/src"
BASE_NAME=$(basename $PWD)

pushd $SRC_ROOT &>/dev/null

for MODULE in $(ls | grep "$BASE_NAME"); do
    cd "$SRC_ROOT/$MODULE"
    if [[ -e './scripts/unpublished' ]]; then
        ./scripts/unpublished
    fi
done

popd &>/dev/null
