#!/bin/bash

for FILE in $(ls $1/images); do
    ITEM=$(basename -s .png $FILE)
    MOD=$(basename $(dirname $1))
    TARGET_DIR="./static/browse/$MOD"
    TARGET_FILE="./static/browse/$MOD/$ITEM/icon.png"

    mkdir -p "$TARGET_DIR"
    mv "$1/$FILE" "$TARGET_FILE"
done
