#!/bin/bash

export AWS_CONFIG_FILE="aws.config"

ROOT="./dist"
SITE="crafting-guide.com"
TARGET=""
while [[ "$1" != "" ]]; do
    case "$1" in
        "--new") TARGET="new";;
        "--promote") TARGET="promote";;
    esac
    shift
done

if [[ "$TARGET" == "" ]]; then
    echo "Please choose either --new or --promote for the target."
    exit
fi

if [[ "$TARGET" == "new" ]]; then
    find . -name ".DS_Store" 2>/dev/null | xargs rm &>/dev/null
    if grunt dist; then
        echo "Preparing to upload to S3..."
        s3cmd sync -r --add-header="cache-control:max-age=1800" "$ROOT/" "s3://new.$SITE/"
        grunt clean:dist build
    else
        echo "Aborting deployment"
    fi
elif [[ "$TARGET" == "promote" ]]; then
    aws s3 sync "s3://new.$SITE" "s3://$SITE" --delete
fi
