#!/bin/bash

BASE_DIR="$1"
for FILE in $(ls $BASE_DIR/images); do
    NAME=$(basename -s.png $FILE)
    DIR="$BASE_DIR/$NAME"
    IMG_DEST="$DIR/icon.png"

    mkdir -p $DIR
    mv "$BASE_DIR/images/$FILE" "$IMG_DEST"
done
