#!/bin/bash

MODULE=$(basename $PWD)
QUIET="NO"
while [[ "$1" != "" ]]; do
    case "$1" in
        "-q") QUIET="YES";;
    esac
    shift
done

CHANGES=$(git log --oneline production..master | while read LINE; do echo "    $LINE"; done)

if [[ "$CHANGES" != "" ]]; then
    printf "\nUndeployed changes for $MODULE:\n$CHANGES\n\n"
elif [[ "$QUIET" == "NO" ]]; then
    printf "No undeployed changes for $MODULE\n\n"
fi

VERSION=$(cat package.json | grep "version" | sed 's/.*"version": "\(.*\)",$/\1/')
CHANGES=$(git log --oneline "v$VERSION"..master | while read LINE; do echo "    $LINE"; done)

if [[ "$CHANGES" != "" ]]; then
    printf "\nUnpublished NPM module changes for $MODULE:\n$CHANGES\n\n"
else
    printf "No unpublished NPM module changes for $MODULE\n\n"
fi
