#!/bin/bash

if [[ -d "../crafting-guide-common" ]]; then
    rm -rf ./node_modules/crafting-guide-common &>/dev/null
    mkdir -p node_modules
    cd node_modules
    ln -s ../../crafting-guide-common
fi
