schema: 1

group: Liquids

    item: Fluid Cyanite

    item: Fluid Cyanite Bucket
        recipe:
            input: Bucket, Fluid Cyanite
            pattern: ... .1. .0.

    item: Fluid Yellorium

    item: Fluid Yellorium Bucket
        recipe:
            input: Bucket, Fluid Yellorium
            pattern: ... .1. .0.

group: Machines

    item: Cyanite Reprocesssor
        recipe:
            input: Iron Ingot, Piston, Reactor Casing, Redstone, Yellorium Fuel Rod
            pattern: 202 141 232
            tools: Crafting Table

group: Minerals

    item: Blutonium Block
        recipe:
            input: Blutonium Ingot
            pattern: 000 000 000
            tools: Crafting Table

    item: Blutonium Dust
        recipe:
            input: Blutonium Ingot
            pattern: ... .0. ...
            tools: Macerator
        recipe:
            input: Blutonium Block
            pattern: ... .0. ...
            quantity: 9
            tools: Macerator
        recipe:
            input: Blutonium Ingot
            pattern: ... .0. ...
            tools: Pulverizer
        recipe:
            input: Blutonium Block
            pattern: ... .0. ...
            quantity: 9
            tools: Pulverizer

    item: Blutonium Ingot
        recipe:
            input: Cyanite Ingot, Water
            pattern: .0. .0. .1.
            tools: Cyanite Reprocesssor
        recipe:
            input: Blutonium Dust, furnace fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Blutonium Block
            pattern: ... .0. ...
            quantity: 9

    item: Cyanite Block
        recipe:
            input: Cyanite Ingot
            pattern: 000 000 000
            tools: Crafting Table

    item: Cyanite Dust
        recipe:
            input: Cyanite Ingot
            pattern: ... .0. ...
            tools: Macerator
        recipe:
            input: Cyanite Block
            pattern: ... .0. ...
            quantity: 9
            tools: Macerator
        recipe:
            input: Cyanite Ingot
            pattern: ... .0. ...
            tools: Pulverizer
        recipe:
            input: Cyanite Block
            pattern: ... .0. ...
            quantity: 9
            tools: Pulverizer

    item: Cyanite Ingot
        recipe:
            input: Sand, Yellorium Ingot
            pattern: ... 10. ...
        recipe:
            input: Cyanite Block
            pattern: ... .0. ...
            quantity: 9

    item: Graphite Bar
        recipe:
            input: Coal, furnace fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Charcoal, furnace fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Graphite Dust, furnace fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Graphite Block
            pattern: ... .0. ...
            quantity: 9

    item: Graphite Block
        recipe:
            input: Graphite Bar
            pattern: 000 000 000
            tools: Crafting Table

    item: Graphite Dust
        recipe:
            input: Graphite Bar
            pattern: ... .0. ...
            tools: Macerator
        recipe:
            input: Graphite Block
            pattern: ... .0. ...
            tools: Macerator
        recipe:
            input: Graphite Bar
            pattern: ... .0. ...
            tools: Pulverizer
        recipe:
            input: Graphite Block
            pattern: ... .0. ...
            tools: Pulverizer

    item: Ludicrite Block
        recipe:
            input: Block of Emerald, Blutonium Ingot, Ender Pearl, Nether Star
            pattern: 121 030 121
            tools: Crafting Table
        recipe:
            input: Ludicrite Ingot
            pattern: 000 000 000
            tools: Crafting Table

    item: Ludicrite Dust
        recipe:
            input: Ludicrite Ingot
            pattern: ... .0. ...
            tools: Macerator
        recipe:
            input: Ludicrite Block
            pattern: ... .0. ...
            tools: Macerator
        recipe:
            input: Ludicrite Ingot
            pattern: ... .0. ...
            tools: Pulverizer
        recipe:
            input: Ludicrite Block
            pattern: ... .0. ...
            tools: Pulverizer

    item: Ludicrite Ingot
        recipe:
            input: Ludicrite Dust, furnace fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Ludicrite Block
            pattern: ... .0. ...
            quantity: 9

    item: Yellorite Ore

    item: Yellorium Block
        recipe:
            input: Yellorium Ingot
            pattern: 000 000 000
            tools: Crafting Table

    item: Yellorium Dust
        recipe:
            input: Yellorium Ingot
            pattern: ... .0. ...
            tools: Macerator
        recipe:
            input: Yellorium Block
            pattern: ... .0. ...
            quantity: 9
            tools: Macerator
        recipe:
            input: Yellorite Ore
            pattern: ... .0. ...
            quantity: 2
            tools: Macerator
        recipe:
            input: Yellorium Ingot
            pattern: ... .0. ...
            tools: Pulverizer
        recipe:
            input: Yellorium Block
            pattern: ... .0. ...
            quantity: 9
            tools: Pulverizer
        recipe:
            input: Yellorite Ore
            pattern: ... .0. ...
            quantity: 2
            tools: Pulverizer

    item: Yellorium Ingot
        recipe:
            input: Yellorite Ore, furnace fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Yellorium Dust, furnace fuel
            pattern: .0. ... .1.
            tools: Furnace
        recipe:
            input: Yellorium Block
            pattern: ... .0. ...
            quantity: 9

group: Reactor Parts

    item: Reactor Access Port
        recipe:
            input: Chest, Piston, Reactor Casing
            pattern: 2.2 .0. 212
            tools: Crafting Table

    item: Reactor Casing
        recipe:
            input: Graphite Bar, Iron Ingot, Yellorium Ingot
            pattern: 101 020 101
            quantity: 4
            tools: Crafting Table

    item: Reactor Computer Port
        recipe:
            input: Gold Ingot, Reactor Casing, Reactor Redstone Port, Redstone
            pattern: 131 020 131
            tools: Crafting Table

    item: Reactor Control Rod
        recipe:
            input: Graphite Bar, Reactor Casing, Redstone, Yellorium Ingot
            pattern: 101 020 131
            tools: Crafting Table

    item: Reactor Controller
        recipe:
            input: Diamond, Reactor Casing, Redstone, Yellorium Ingot
            pattern: 1.1 303 121
            tools: Crafting Table

    item: Reactor Coolant Port
        recipe:
            input: Bucket, Iron Ingot, Piston, Reactor Casing
            pattern: 3.3 101 323
            tools: Crafting Table

    item: Reactor Glass
        recipe:
            input: Glass, Reactor Casing
            pattern: ... 010 ...
            tools: Crafting Table

    item: Reactor Power Tap
        recipe:
            input: Reactor Casing, Redstone
            pattern: 010 1.1 010
            tools: Crafting Table

    item: Reactor RedNet Port
        recipe:
            input: Gold Ingot, Reactor Casing, RedNet Cable
            pattern: 121 202 121
            tools: Crafting Table

    item: Reactor Redstone Port
        recipe:
            input: Gold Ingot, Reactor Casing, Redstone
            pattern: 121 202 121
            tools: Crafting Table

    item: Yellorium Fuel Rod
        recipe:
            input: Graphite Bar, Iron Ingot, Yellorium Ingot
            pattern: 101 121 101
            tools: Crafting Table

group: Turbine Parts

    item: Turbine Computer Port
        recipe:
            input: Gold Ingot, Redstone, Redstone Repeater, Turbine Housing
            pattern: 313 020 313
            tools: Crafting Table

    item: Turbine Controller
        recipe:
            input: Blutonium Ingot, Diamond, Turbine Housing
            pattern: 2.2 010 2.2
            tools: Crafting Table

    item: Turbine Fluid Port
        recipe:
            input: Bucket, Iron Ingot, Piston, Turbine Housing
            pattern: 3.3 101 323
            tools: Crafting Table

    item: Turbine Glass
        recipe:
            input: Glass, Turbine Housing
            pattern: ... 010 ...
            tools: Crafting Table

    item: Turbine Housing
        recipe:
            input: Blutonium Ingot, Graphite Bar, Iron Ingot, Nether Quartz
            pattern: 212 303 212
            quantity: 4
            tools: Crafting Table

    item: Turbine Power Port
        recipe:
            input: Redstone, Turbine Housing
            pattern: 101 0.0 101
            tools: Crafting Table

    item: Turbine Rotor Bearing
        recipe:
            input: Diamond, Turbine Housing, Turbine Rotor Shaft
            pattern: 121 000 121
            tools: Crafting Table

    item: Turbine Rotor Blade
        recipe:
            input: Cyanite Ingot, Iron Ingot
            pattern: ... 011 ...
            tools: Crafting Table

    item: Turbine Rotor Shaft
        recipe:
            input: Cyanite Ingot, Iron Ingot
            pattern: ... 101 ...
            tools: Crafting Table
