schema: 1

name:             EnderIO
author:           CrazyPants
description:      Compact fluid, item, power and redstone conduits, power generation, machinery, remote area access (EnderIO), Dimensional Transceivers, and new armor & tools
homePageUrl:      http://enderio.com/
documentationUrl: http://wiki.enderio.com/Main_Page
downloadUrl:      http://minecraft.curseforge.com/mc-mods/64578-ender-io/files

version: 2.2.7.325
